/**
 * Officiella referensdata och mallar för MUF, MSU och MST
 * Per den 31 december 2025.
 */

export const ORG_CONFIGS = {
  muf: {
    key: 'muf',
    name: 'Moderata Ungdomsförbundet (MUF)',
    shortName: 'MUF',
    assemblyName: 'Förbundsstämman',
    unitTypeLabel: 'Distrikt',
    targetSeats: 101,
    minSeats: 2,
    thresholdFormula: 'max(2, round(M / D))',
    description: '25 distrikt med minst 2 grundmandat per distrikt.',
    defaultData: [
      { id: 'muf-sthlm', name: 'MUF Stockholm', members: 4193 },
      { id: 'muf-skane', name: 'MUF Skåne', members: 3348 },
      { id: 'muf-ostergotland', name: 'MUF Östergötland', members: 1631 },
      { id: 'muf-jonkoping', name: 'MUF Jönköping', members: 1301 },
      { id: 'muf-goteborg', name: 'MUF Göteborg', members: 1230 },
      { id: 'muf-uppsala', name: 'MUF Uppsala', members: 913 },
      { id: 'muf-halland', name: 'MUF Halland', members: 748 },
      { id: 'muf-sodermanland', name: 'MUF Södermanland', members: 649 },
      { id: 'muf-vgv', name: 'MUF Västra Götaland Västra', members: 545 },
      { id: 'muf-orebro', name: 'MUF Örebro', members: 477 },
      { id: 'muf-salvsborg', name: 'MUF Södra Älvsborg', members: 464 },
      { id: 'muf-skaraborg', name: 'MUF Skaraborg', members: 463 },
      { id: 'muf-vasternorrland', name: 'MUF Västernorrland', members: 438 },
      { id: 'muf-kronoberg', name: 'MUF Kronoberg', members: 421 },
      { id: 'muf-varmland', name: 'MUF Värmland', members: 372 },
      { id: 'muf-vasterbotten', name: 'MUF Västerbotten', members: 325 },
      { id: 'muf-vastmanland', name: 'MUF Västmanland', members: 270 },
      { id: 'muf-fyrbodal', name: 'MUF Fyrbodal', members: 267 },
      { id: 'muf-norrbotten', name: 'MUF Norrbotten', members: 255 },
      { id: 'muf-kalmar', name: 'MUF Kalmar', members: 251 },
      { id: 'muf-gavleborg', name: 'MUF Gävleborg', members: 238 },
      { id: 'muf-jamtland', name: 'MUF Jämtland', members: 221 },
      { id: 'muf-dalarna', name: 'MUF Dalarna', members: 214 },
      { id: 'muf-blekinge', name: 'MUF Blekinge', members: 102 },
      { id: 'muf-gotland', name: 'MUF Gotland', members: 87 }
    ]
  },
  msu: {
    key: 'msu',
    name: 'Moderat Skolungdom (MSU)',
    shortName: 'MSU',
    assemblyName: 'Nationella Stämman',
    unitTypeLabel: 'Distrikt',
    targetSeats: 51,
    minSeats: 1,
    thresholdFormula: 'max(1, round(M / D))',
    description: '25 distrikt med minst 1 grundmandat per distrikt.',
    defaultData: [
      { id: 'msu-sthlm', name: 'MUF Stockholm', members: 3636 },
      { id: 'msu-skane', name: 'MUF Skåne', members: 3014 },
      { id: 'msu-ostergotland', name: 'MUF Östergötland', members: 1322 },
      { id: 'msu-goteborg', name: 'MUF Göteborg', members: 1039 },
      { id: 'msu-jonkoping', name: 'MUF Jönköping', members: 995 },
      { id: 'msu-uppsala', name: 'MUF Uppsala', members: 812 },
      { id: 'msu-halland', name: 'MUF Halland', members: 647 },
      { id: 'msu-sodermanland', name: 'MUF Södermanland', members: 561 },
      { id: 'msu-vgv', name: 'MUF Västra Götaland Västra', members: 491 },
      { id: 'msu-salvsborg', name: 'MUF Södra Älvsborg', members: 415 },
      { id: 'msu-vasternorrland', name: 'MUF Västernorrland', members: 400 },
      { id: 'msu-orebro', name: 'MUF Örebro', members: 387 },
      { id: 'msu-skaraborg', name: 'MUF Skaraborg', members: 381 },
      { id: 'msu-kronoberg', name: 'MUF Kronoberg', members: 359 },
      { id: 'msu-varmland', name: 'MUF Värmland', members: 298 },
      { id: 'msu-vasterbotten', name: 'MUF Västerbotten', members: 254 },
      { id: 'msu-fyrbodal', name: 'MUF Fyrbodal', members: 241 },
      { id: 'msu-vastmanland', name: 'MUF Västmanland', members: 233 },
      { id: 'msu-kalmar', name: 'MUF Kalmar', members: 214 },
      { id: 'msu-gavleborg', name: 'MUF Gävleborg', members: 200 },
      { id: 'msu-norrbotten', name: 'MUF Norrbotten', members: 197 },
      { id: 'msu-jamtland', name: 'MUF Jämtland', members: 193 },
      { id: 'msu-dalarna', name: 'MUF Dalarna', members: 188 },
      { id: 'msu-blekinge', name: 'MUF Blekinge', members: 82 },
      { id: 'msu-gotland', name: 'MUF Gotland', members: 77 }
    ]
  },
  mst: {
    key: 'mst',
    name: 'Moderata Studenter (MST)',
    shortName: 'MST',
    assemblyName: 'Studentstämman',
    unitTypeLabel: 'Förening / Lärosäte',
    targetSeats: 51,
    minSeats: 0,
    thresholdFormula: 'max(0, round(M / D))',
    description: '26 studentföreningar/lärosäten utan grundmandat (effektiv spärr vid M >= 14).',
    defaultData: [
      { id: 'mst-jonkoping', name: 'MST Jönköping', members: 362 },
      { id: 'mst-goteborg', name: 'MST Göteborg', members: 251 },
      { id: 'mst-linkoping', name: 'MST Linköping', members: 207 },
      { id: 'mst-sthlm', name: 'MST Stockholms län', members: 104 },
      { id: 'mst-skovde', name: 'MST Skövde', members: 83 },
      { id: 'mst-umea', name: 'MST Umeå', members: 65 },
      { id: 'mst-uppsala', name: 'MST Uppsala', members: 52 },
      { id: 'mst-lund', name: 'MST Lunds universitet', members: 43 },
      { id: 'mst-halmstad', name: 'MST Halmstad', members: 41 },
      { id: 'mst-vaxjo', name: 'MST Växjö', members: 31 },
      { id: 'mst-orebro', name: 'MST Örebro', members: 30 },
      { id: 'mst-boras', name: 'MST Borås', members: 29 },
      { id: 'mst-kalmar', name: 'MST Kalmar', members: 27 },
      { id: 'mst-karlstad', name: 'MST Karlstad', members: 27 },
      { id: 'mst-norrkoping', name: 'MST Norrköping', members: 20 },
      { id: 'mst-malmo', name: 'MST Malmö', members: 18 },
      { id: 'mst-lulea', name: 'MST Luleå', members: 7 },
      { id: 'mst-kth', name: 'MST KTH', members: 5 },
      { id: 'mst-mittuni', name: 'MST Mittuniversitetet', members: 5 },
      { id: 'mst-su', name: 'MST SU', members: 4 },
      { id: 'mst-mdu', name: 'MST MDU', members: 3 },
      { id: 'mst-hhs', name: 'MST Handelshögskolan', members: 2 },
      { id: 'mst-blekinge', name: 'MST Blekinge', members: 1 },
      { id: 'mst-fhs', name: 'MST Försvarshögskolan', members: 1 },
      { id: 'mst-mittuni-ostersund', name: 'MST Mittuniversitetet Östersund', members: 0 },
      { id: 'mst-sodertorn', name: 'MST Södertörn', members: 0 }
    ]
  },
  custom: {
    key: 'custom',
    name: 'Anpassad Fördelning',
    shortName: 'Egen stämma',
    assemblyName: 'Stämma / Årsmöte',
    unitTypeLabel: 'Enhet / Förening',
    targetSeats: 100,
    minSeats: 1,
    thresholdFormula: 'max(min_grundmandat, round(M / D))',
    description: 'Valfri organisation med fullt anpassningsbara parametrar.',
    defaultData: [
      { id: 'custom-1', name: 'Klubb Alfa', members: 450 },
      { id: 'custom-2', name: 'Klubb Beta', members: 320 },
      { id: 'custom-3', name: 'Klubb Gamma', members: 210 },
      { id: 'custom-4', name: 'Klubb Delta', members: 115 },
      { id: 'custom-5', name: 'Klubb Epsilon', members: 45 }
    ]
  }
};
